[package]
name = "triangle_filler"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
egui_sdl2_gl = "0.23.0"
sdl2 = "0.35.2"
glam = "0.24.2"
image = "0.24.7"

